# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sd2026.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sd2026.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csd2026.proto\x12\x06sd2026\"H\n\x0fGreetingRequest\x12\x11\n\tfrom_port\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"I\n\x10GreetingResponse\x12\x11\n\tfrom_port\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"=\n\x08NodeInfo\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x15\n\rregistered_at\x18\x03 \x01(\t\"-\n\x0fRegisterRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"/\n\x11UnregisterRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"%\n\x12UnregisterResponse\x12\x0f\n\x07removed\x18\x01 \x01(\x08\"L\n\x10RegisterResponse\x12\x17\n\x0f\x61ssigned_window\x18\x01 \x01(\t\x12\x1f\n\x05peers\x18\x02 \x03(\x0b\x32\x10.sd2026.NodeInfo\"\x0f\n\rHealthRequest\"x\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x18\n\x10registered_nodes\x18\x02 \x01(\x05\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x01\x12\x11\n\tgrpc_port\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"\x0e\n\x0cNodesRequest\"?\n\rNodesResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x1f\n\x05nodes\x18\x02 \x03(\x0b\x32\x10.sd2026.NodeInfo2M\n\x0fGreetingService\x12:\n\x05Greet\x12\x17.sd2026.GreetingRequest\x1a\x18.sd2026.GreetingResponse2\x87\x02\n\x0fRegistryService\x12=\n\x08Register\x12\x17.sd2026.RegisterRequest\x1a\x18.sd2026.RegisterResponse\x12\x43\n\nUnregister\x12\x19.sd2026.UnregisterRequest\x1a\x1a.sd2026.UnregisterResponse\x12\x37\n\x06Health\x12\x15.sd2026.HealthRequest\x1a\x16.sd2026.HealthResponse\x12\x37\n\x08GetNodes\x12\x14.sd2026.NodesRequest\x1a\x15.sd2026.NodesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sd2026_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GREETINGREQUEST']._serialized_start=24
  _globals['_GREETINGREQUEST']._serialized_end=96
  _globals['_GREETINGRESPONSE']._serialized_start=98
  _globals['_GREETINGRESPONSE']._serialized_end=171
  _globals['_NODEINFO']._serialized_start=173
  _globals['_NODEINFO']._serialized_end=234
  _globals['_REGISTERREQUEST']._serialized_start=236
  _globals['_REGISTERREQUEST']._serialized_end=281
  _globals['_UNREGISTERREQUEST']._serialized_start=283
  _globals['_UNREGISTERREQUEST']._serialized_end=330
  _globals['_UNREGISTERRESPONSE']._serialized_start=332
  _globals['_UNREGISTERRESPONSE']._serialized_end=369
  _globals['_REGISTERRESPONSE']._serialized_start=371
  _globals['_REGISTERRESPONSE']._serialized_end=447
  _globals['_HEALTHREQUEST']._serialized_start=449
  _globals['_HEALTHREQUEST']._serialized_end=464
  _globals['_HEALTHRESPONSE']._serialized_start=466
  _globals['_HEALTHRESPONSE']._serialized_end=586
  _globals['_NODESREQUEST']._serialized_start=588
  _globals['_NODESREQUEST']._serialized_end=602
  _globals['_NODESRESPONSE']._serialized_start=604
  _globals['_NODESRESPONSE']._serialized_end=667
  _globals['_GREETINGSERVICE']._serialized_start=669
  _globals['_GREETINGSERVICE']._serialized_end=746
  _globals['_REGISTRYSERVICE']._serialized_start=749
  _globals['_REGISTRYSERVICE']._serialized_end=1012
# @@protoc_insertion_point(module_scope)